# -*- coding: utf-8 -*-
"""data mining k-mean

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oe-HU4kWelqyW8Q-5Fk8i4FdcDN-Qepk
"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import pandas as pd

df = pd.DataFrame({
    'x' : [12,20,58,12,29,33,24,35,75,52,59,52,75,53,55,61,64,69,72,13,43,56,76,12,34,33,55,12,65],
    'y' : [39,31,10,51,54,46,55,69,13,71,66,67,58,23,14,8,19,7,24,12,45,65,77,33,23,56,77,12,56]
})

kmeans = KMeans(n_clusters=3)
kmeans.fit(df)

labels = kmeans.predict(df)
centroids = kmeans.cluster_centers_

fig = plt.figure(figsize = (5,5))

colmap = {1 : 'r', 2 : 'g', 3 : 'b'}
colors = map(lambda x: colmap[x+1], labels)
colors1 = list(colors)
plt.scatter(df['x'], df['y'], color = colors1, alpha = 0.5, edgecolor = 'k')
for idx, centroid in enumerate(centroids):
  plt.scatter(*centroid, color = colmap[idx+1])
plt.xlim(0,80)
plt.ylim(0,80)
plt.show()